apiVersion: v1
kind: Secret
metadata:
  name: mindforge-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017/mindforge
  ANTHROPIC_API_KEY: your-key-here
  SECRET_KEY: super-secret-key
